// CATEGORIES
export const FETCH_CATEGORIES_DATA = "FETCH_CATEGORIES_DATA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

// ITEMS IN CATEGORY
export const FETCH_ALL_ITEMS_DATA = "FETCH_ALL_ITEMS_DATA";
export const FETCH_ALL_ITEMS_SUCCESS = "FETCH_ALL_ITEMS_SUCCESS";
export const FETCH_ALL_ITEMS_FAILURE = "FETCH_ALL_ITEMS_FAILURE";

// ADD ITEM TO CATEGORY
export const ADD_ITEM_TO_CATEGORY = "ADD_ITEM_TO_CATEGORY";
export const ADD_ITEM_TO_CATEGORY_SUCCESS = "ADD_ITEM_TO_CATEGORY_SUCCESS";
export const ADD_ITEM_TO_CATEGORY_FAILURE = "ADD_ITEM_TO_CATEGORY_FAILURE";

// TOGGLE ITEM COMPLETE
export const TOGGLE_ITEM_COMPLETE = "TOGGLE_ITEM_COMPLETE";
export const TOGGLE_ITEM_COMPLETE_SUCCESS = "TOGGLE_ITEM_COMPLETE_SUCCESS";
export const TOGGLE_ITEM_COMPLETE_FAILURE = "TOGGLE_ITEM_COMPLETE_FAILURE";

// FETCH ITEM
export const FETCH_ITEM = "FETCH_ITEM";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE";

// EDIT ITEM
export const EDIT_ITEM = "EDIT_ITEM";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAILURE = "EDIT_ITEM_FAILURE";

// DELETE ITEM
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";

// DELETE ALL ITEMS
export const DELETE_ALL_ITEMS = "DELETE_ALL_ITEMS";
export const DELETE_ALL_ITEMS_SUCCESS = "DELETE_ALL_ITEMS_SUCCESS";
export const DELETE_ALL_ITEMS_FAILURE = "DELETE_ALL_ITEMS_FAILURE";
