// CATEGORIES
export const FETCH_CATEGORIES_DATA = "FETCH_CATEGORIES_DATA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const RESET_CATEGORIES_DATA = "RESET_CATEGORIES_DATA";

// ITEMS IN CATEGORY
export const FETCH_CATEGORY_ITEMS_DATA = "FETCH_CATEGORY_ITEMS_DATA";
export const FETCH_CATEGORY_ITEMS_SUCCESS = "FETCH_CATEGORY_ITEMS_SUCCESS";
export const FETCH_CATEGORY_ITEMS_FAILURE = "FETCH_CATEGORY_ITEMS_FAILURE";
export const RESET_CATEGORY_ITEMS_DATA = "RESET_CATEGORY_ITEMS_DATA";

// ADD ITEM TO CATEGORY
export const ADD_ITEM_TO_CATEGORY = "ADD_ITEM_TO_CATEGORY";
export const ADD_ITEM_TO_CATEGORY_SUCCESS = "ADD_ITEM_TO_CATEGORY_SUCCESS";
export const ADD_ITEM_TO_CATEGORY_FAILURE = "ADD_ITEM_TO_CATEGORY_FAILURE";
